// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const insertField = `-- name: InsertField :one
INSERT INTO
    fields (name, dashed_name, flat_name, type, level, short, description, example)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    RETURNING id
`

type InsertFieldParams struct {
	Name        string
	DashedName  string
	FlatName    string
	Type        string
	Level       string
	Short       sql.NullString
	Description sql.NullString
	Example     sql.NullString
}

func (q *Queries) InsertField(ctx context.Context, arg InsertFieldParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertField,
		arg.Name,
		arg.DashedName,
		arg.FlatName,
		arg.Type,
		arg.Level,
		arg.Short,
		arg.Description,
		arg.Example,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
